import type { Metadata } from 'next'
import '../globals.css'
import { fontQuestrial, fontUrbanist } from '@/utils/font'
import Sidebar from '@/components/layouts/Sidebar'
import HeaderBar from '@/components/layouts/HeaderBar'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${fontUrbanist.variable} ${fontQuestrial.variable} flex items-start justify-between bg-[#E4F4F9]`}
			>
				<Sidebar />
				<main className='pl-60 w-full h-full flex flex-col gap-4'>
					<HeaderBar />
					{children}
				</main>
			</body>
		</html>
	)
}
